"""initial migration

Revision ID: 5c0e37da31b6
Revises: 
Create Date: 2025-03-12 15:36:52.878284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0e37da31b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('control_ac', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('second_company_name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('address_3', sa.String(), nullable=True),
    sa.Column('post_code', sa.String(), nullable=True),
    sa.Column('tin', sa.String(), nullable=True),
    sa.Column('id_type', sa.String(), nullable=True),
    sa.Column('id_no', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_index', sa.Integer(), nullable=False),
    sa.Column('sales_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('control_ac', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('second_company_name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('address_3', sa.String(), nullable=True),
    sa.Column('post_code', sa.String(), nullable=True),
    sa.Column('tin', sa.String(), nullable=True),
    sa.Column('id_type', sa.String(), nullable=True),
    sa.Column('id_no', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    op.drop_table('settings')
    op.drop_table('customers')
    # ### end Alembic commands ###
